### ISSUE TITLE
Repeats the sentence I say instead of the one I said before (German/ de-de)

### ISSUE THREAD

**Issue by Loopinglu** [MycroftAI/skill-repeat-interactions#3]
Well maybe I don't get the point of this skill but mycroft always just repeats the command I give like "Was habe ich gerade gesagt?" (What did I just say?) it answers, "Du hast einfach nur gesagt, was habe ich gerade gesagt" (You just said, what did I just say).

Is that how it's meant to work??

**Comment by krisgesling** [comment]
My quick read of the code says this is to be expected, but can't be what is intended. I'm assuming this is why it isn't in the Marketplace. 

It hasn't had an update in a long time so if anyone is keen to see it returned then please consider generating a PR. Feel free to ask any questions here or in the [~Skills channel of Chat](https://chat.mycroft.ai/community/channels/skills) if you want any pointers to get started.
